AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  MovieReleaseTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Title"
          AttributeType: "S"
        - 
          AttributeName: "Genre"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Title"
          KeyType: "HASH"
        - 
          AttributeName: "Genre"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "Movie_Release_Table"
  LUITRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Path: /
      RoleName: LUITRole  
  LUITInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: LUITInstanceProfile
      Path: /
      Roles: 
        - !Ref LUITRole
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      IamInstanceProfile: !Ref LUITInstanceProfile
      ImageId: ami-0fff1b9a61dec8a5f
      InstanceType: t2.micro
      KeyName: keypairforluitccp3
      SecurityGroupIds: 
        - sg-00d40412bcd8cbb19
      SubnetId: subnet-036b945f62258a699